### ISSUE TITLE
Create public repository for swift api client

### ISSUE THREAD

**Issue by kevinwoolfolk97** [CardScan-ai/api-clients#24]
### Overview:

**Is your feature request related to a problem? Please describe.**
 Swift API client need to be public to be integrated into the SDK.

**Describe the solution you'd like**
I would like to create a public repository for the Swift API client, allowing developers to access.

### Goal:
A public repository for the Swift API client.

### Tasks
- [ ] Create a new public repository for the Swift API client.
- [ ] Add a README file with an overview, installation instructions, usage examples, and contribution guidelines.

### Acceptance Criteria
- [ ] The repository includes the current Swift API client code.
