### ISSUE TITLE
Add missing summary-related properties and hooks.

### ISSUE THREAD

**Issue by kevinwoolfolk97** [CardScan-ai/api-clients#34]
### Overview:

**Is your feature request related to a problem? Please describe.**
We needed some changes requested by Alexis when implementing models in the Kotlin SDKs, this changes need to apply to all the models.

### Tasks
- [ ] Add missing properties to summary related models
- [ ] Use existing eligibility summarization model instead of making `eligibility_summarized_response` field generic
- [ ] Add pre-commit hook to format yaml and lint openapi spec file (had to rename file to openapi.yaml)
