### ISSUE TITLE
Generate kotlin client variants, with updated name

### ISSUE THREAD

**Issue by alexisInowuDev** [CardScan-ai/api-clients#74]
### Overview:

**Is your feature request related to a problem? Please describe.**
The use of moshi library for deserialization is making us opt in to an experimental feature, which might have CardScan clients set flags to accept this features. We want to avoid this, as clients do not like to mess with experimental features. Also, we want to change the default name for the client package.

**Describe the solution you'd like**
Generate two variants of the kotlin client: 

1. `serializationLibrary = kotlinx_serialization`, everything else as usual
2. `moshiCodeGen  = true`, everything else as usual
 
Both variants should update the packageName to `cardscan.ai.client`

### Goal:
Remove the need to opt in to experimental features.

### Tasks
- [x] Generate both variants, in separate branches.
- [x] Test them ( @alexisInowuDev will take care of this )

### Acceptance Criteria
- [x] Kotlin client should keep working well, as it already is, but opting in to experimental features is no longer needed. 
- [x] Package name has been updated.
